apiVersion: deploy.cloud.google.com/v1
kind: DeliveryPipeline
metadata:
  name: sre
description: Simple application delivery pipeline
serialPipeline:
 stages:
 - targetId: dev
 - targetId: pre
   profiles:
   - pre
 - targetId: pro
   profiles:
   - pro
---

apiVersion: deploy.cloud.google.com/v1
kind: Target
metadata:
  name: dev
description: dev cluster
gke:
  cluster: projects/My First Project/locations/europe-west1/clusters/my-gke-cluster
---

apiVersion: deploy.cloud.google.com/v1
kind: Target
metadata:
  name: pre
description: pre cluster
gke:
  cluster: projects/My First Project/locations/europe-west1/clusters/my-gke-cluster
---

apiVersion: deploy.cloud.google.com/v1
kind: Target
metadata:
  name: pro
description: pro cluster
requireApproval: true
gke:
  cluster: projects/My First Project/locations/europe-west1/clusters/my-gke-cluster